export const SET_SERCHED_LEDAMOTER = 'SET_SERCHED_LEDAMOTER';

export const ADD_LEDAMOT='ADD_LEDAMOT';

//Actions for navigation experim
export const NAVIGATION_FORWARD='NAVIGATION_FORWARD';
export const NAVIGATION_BACK='NAVIGATION_BACK';
